version: "3.9"

services:
  database:
    image: mariadb:10.6
    environment:
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=uft8mb4
      - MARIADB_COLLATE=uft8mb4_unicode_ci
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/moodle:/var/www/html/moodle
      - ./src/moodle_data:/var/www/html/moodle_data
      - ./src/info.php:/var/www/html/info.php
    links:
      - php

  php:
    build:
      dockerfile: php.Dockerfile
    volumes:
      - ./src/moodle:/var/www/html/moodle
      - ./src/moodle_data:/var/www/html/moodle_data
      - ./src/info.php:/var/www/html/info.php
      - ./php/conf.d:/usr/local/etc/php/conf.d
